'use server';

/**
 * @fileOverview This file defines a Genkit flow that provides tailored feedback generated by AI for improvement based on analyzed insights from user-provided sentences.
 *
 * @file OfferTailoredFeedbackFlow - A Genkit flow to offer tailored feedback based on sentence analysis.
 * @file OfferTailoredFeedbackInput - The input type for the OfferTailoredFeedback flow.
 * @file OfferTailoredFeedbackOutput - The output type for the OfferTailoredFeedback flow.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OfferTailoredFeedbackInputSchema = z.object({
  sentences: z
    .array(z.string())
    .length(5)
    .describe('An array containing five sentences provided by the user.'),
  inferredQualities: z.string().describe('Inferred qualities from the input sentences.'),
  sentimentAnalysis: z.string().describe('Sentiment analysis of the input sentences.'),
  personalityInsights: z.string().describe('Personality insights derived from the sentence associations.'),
});
export type OfferTailoredFeedbackInput = z.infer<typeof OfferTailoredFeedbackInputSchema>;

const OfferTailoredFeedbackOutputSchema = z.object({
  tailoredFeedback: z.string().describe('Tailored feedback for improvement based on the analyzed insights.'),
});
export type OfferTailoredFeedbackOutput = z.infer<typeof OfferTailoredFeedbackOutputSchema>;

export async function offerTailoredFeedback(input: OfferTailoredFeedbackInput): Promise<OfferTailoredFeedbackOutput> {
  return offerTailoredFeedbackFlow(input);
}

const offerTailoredFeedbackPrompt = ai.definePrompt({
  name: 'offerTailoredFeedbackPrompt',
  input: {schema: OfferTailoredFeedbackInputSchema},
  output: {schema: OfferTailoredFeedbackOutputSchema},
  prompt: `You are a psychologist providing feedback to a candidate.
  You will provide tailored feedback for improvement based on the analyzed insights of a candidate's provided sentences.

  Based on the following information, offer tailored feedback for the candidate to improve their thought processes and communication.

  Inferred Qualities: {{{inferredQualities}}}
  Sentiment Analysis: {{{sentimentAnalysis}}}
  Personality Insights: {{{personalityInsights}}}

  Provide specific and actionable feedback that the candidate can use to refine their perspectives.
  The feedback should be encouraging and constructive.
  Do not mention that the feedback is being generated by AI.
  Do not mention the input sentences.
  `,
});

const offerTailoredFeedbackFlow = ai.defineFlow(
  {
    name: 'offerTailoredFeedbackFlow',
    inputSchema: OfferTailoredFeedbackInputSchema,
    outputSchema: OfferTailoredFeedbackOutputSchema,
  },
  async input => {
    const {output} = await offerTailoredFeedbackPrompt(input);
    return output!;
  }
);
